# Rainstorm Parameters file

# Path to the folder containing the pose estimation files
path: C:\Users\dhers\Desktop\Rainstorm\docs\examples\NOR

# Pose estimation filenames
filenames:
- NOR_Hab_C1
- NOR_Hab_C2
- NOR_Hab_C3
- NOR_Hab_C4
- NOR_Hab_C5
- NOR_TR_C1
- NOR_TR_C2
- NOR_TR_C3
- NOR_TR_C4
- NOR_TR_C5
- NOR_TS_C1
- NOR_TS_C2
- NOR_TS_C3
- NOR_TS_C4
- NOR_TS_C5

# Software used to generate the pose estimation files ('DLC' or 'SLEAP')
software: DLC

# Video frames per second
fps: 25

# Tracked bodyparts
bodyparts:
- nose
- L_ear
- R_ear
- head
- neck
- body
- tail_1
- tail_2
- tail_3

# Exploration targets
targets:
- obj_1
- obj_2

# Parameters for processing positions
prepare_positions:

  # How many std_dev away from the mean the point's likelihood can be without being erased
  confidence: 2

  # If the mean likelihood is below this value, the whole point will be erased
  tolerance: 0.8

  # Number of frames to use for the median filter (it must be an odd number)
  median_filter: 3

# Parameters for geometric analysis
geometric_analysis:

  # Loaded from ROIs.json
  roi_data:

    # Shape of the video frames ([width, height])
    frame_shape:
    - 720
    - 640

    # Scale factor (in px/cm)
    scale: 18.41

    # Defined ROIs (areas) in the frame
    areas:
    - name: left_area
      center:
      - 221
      - 156
      width: 115
      height: 115
      angle: 0
    - name: right_area
      center:
      - 502
      - 156
      width: 115
      height: 115
      angle: 0

    # Key points within the frame
    points: []

  # Maximum nose-target distance to consider exploration
  distance: 2.5

  # Maximum head-target orientation angle to consider exploration
  orientation: 45.0

  # Movement threshold to consider freezing, computed as the mean std of all body parts over 1 second
  freezing_threshold: 0.01

# Parameters for automatic analysis
automatic_analysis:

  # Path to the model file
  model_path: C:\Users\dhers\Desktop\Rainstorm\docs\models\trained_models\example_wide.keras

  # List of bodyparts used to train the model
  model_bodyparts:
  - nose
  - L_ear
  - R_ear
  - head
  - neck
  - body

  # Whether to rescale the data
  rescaling: true

  # Whether to reshape the data (set to True for RNN models)
  reshaping: true

  # Defines the shape of the RNN model
  RNN_width:

    # Number of past frames to include
    past: 3

    # Number of future frames to include
    future: 3

    # Broaden the window by skipping some frames as we stray further from the present
    broad: 1.7

# Parameters for the analysis of the experiment results
seize_labels:

  # Experimental groups you want to compare
  groups:
  - Group_1
  - Group_2

  # If your experiment has multiple trials, list the trial names here
  trials:
  - Hab
  - TR
  - TS

  # Role/novelty of each target in the experiment
  target_roles:
    Hab: null
    TR:
    - Left
    - Right
    TS:
    - Novel
    - Known

  # Type of labels used to measure exploration (geolabels, autolabels, labels, etc)
  label_type: autolabels
