#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 21 15:22:01 2024

@author: usuario
"""

import os

def rename_files(folder_path):
    # Get a list of all files in the folder
    files = os.listdir(folder_path)
    
    # Iterate through each file
    for filename in files:
        # Get the full path of the file
        full_path = os.path.join(folder_path, filename)
        
        # Check if the item is a file
        if os.path.isfile(full_path):
            # Rename the file
            new_filename = filename.replace(".mp4", "_video.mp4")
            
            # Construct the new full path
            new_full_path = os.path.join(folder_path, new_filename)
            
            # Rename the file
            os.rename(full_path, new_full_path)
            print(f"Renamed '{filename}' to '{new_filename}'")

# Specify the folder path
folder_path = '/home/usuario/Desktop/selection'

# Call the function to rename files in the specified folder
rename_files(folder_path)