# Rainstorm Parameters file

# Path to the folder containing the pose estimation files
path: C:\Users\dhers\Desktop\Rainstorm\docs\examples\PD

# Pose estimation filenames
filenames:
- 2024_05-PD-TS-R13_C6n
- 2024_05-PD-TS-R14_C6i
- 2024_05-PD-TS-R15_C6d
- 2024_05-PD-TS-R16_C6a
- 2024_05-PD-TS-R17_C7n
- 2024_05-PD-TS-R18_C7i
- 2024_05-PD-TS-R19_C7d
- 2024_05-PD-TS-R21_C8n
- 2024_05-PD-TS-R22_C8i
- 2024_05-PD-TS-R23_C8d
- 2024_05-PD-TS-R24_C8a
- 2025_04-PD-TS-R01_C1i
- 2025_04-PD-TS-R02_C1n
- 2025_04-PD-TS-R03_C1d
- 2025_04-PD-TS-R04_C1a
- 2025_04-PD-TS-R05_C2n
- 2025_04-PD-TS-R06_C2d
- 2025_04-PD-TS-R07_C2i
- 2025_04-PD-TS-R08_C2a
- 2025_04-PD-TS-R09_C3i
- 2025_04-PD-TS-R10_C3d
- 2025_04-PD-TS-R11_C4i
- 2025_04-PD-TS-R12_C5i

# Software used to generate the pose estimation files ('DLC' or 'SLEAP')
software: DLC

# Video frames per second
fps: 30

# Tracked bodyparts
bodyparts:
- body
- head
- left_ear
- left_hip
- left_midside
- left_shoulder
- neck
- nose
- right_ear
- right_hip
- right_midside
- right_shoulder
- tail_base
- tail_end
- tail_mid

# Exploration targets
targets:
- obj_1
- obj_2

# Parameters for processing positions
prepare_positions:

  # How many std_dev away from the mean the point's likelihood can be without being erased
  confidence: 2

  # Number of frames to use for the median filter (it must be an odd number)
  median_filter: 3

# Parameters for geometric analysis
geometric_analysis:

  # Loaded from ROIs.json
  roi_data:

    # Shape of the video frames ([width, height])
    frame_shape:
    - 720
    - 480

    # Scale factor (in px/cm)
    scale: 18.72

    # Defined ROIs (areas) in the frame
    areas: []

    # Key points within the frame
    points:
    - name: obj_1
      center:
      - 227
      - 137
    - name: obj_2
      center:
      - 491
      - 137

  # Maximum nose-target distance to consider exploration
  distance: 2.5

  # Set up orientation analysis
  orientation:

    # Maximum head-target orientation angle to consider exploration (in degrees)
    degree: 45

    # Ending bodypart of the orientation line
    front: nose

    # Starting bodypart of the orientation line
    pivot: head

  # Movement threshold to consider freezing, computed as the mean std of all body parts over 1 second
  freezing_threshold: 0.01

# Parameters for automatic analysis
automatic_analysis:

  # Path to the model file
  model_path: C:\Users\dhers\Desktop\Rainstorm\docs\models\trained_models\example_wide.keras

  # List of bodyparts used to train the model
  model_bodyparts:
  - nose
  - left_ear
  - right_ear
  - head
  - neck
  - body

  # Whether to rescale the data
  rescaling: true

  # Whether to reshape the data (set to True for RNN models)
  reshaping: true

  # Defines the shape of the RNN model
  RNN_width:

    # Number of past frames to include
    past: 3

    # Number of future frames to include
    future: 3

    # Broaden the window by skipping some frames as we stray further from the present
    broad: 1.7

# Parameters for the analysis of the experiment results
seize_labels:

  # Experimental groups you want to compare
  groups:
  - PD
  - Veh

  # If your experiment has multiple trials, list the trial names here
  trials:
  - TS

  # Role/novelty of each target in the experiment
  target_roles:
    TS:
    - Novel
    - Known

  # Type of labels used to measure exploration (geolabels, autolabels, labels, etc)
  label_type: geolabels
