# Rainstorm Parameters file

# Path to the folder containing the pose estimation files
path: C:\Users\dhers\Desktop\Rainstorm\docs\examples\Y_Maze

# List of the pose estimation filenames
filenames:
- 2025_03-Y_Maze-R01_C1i
- 2025_03-Y_Maze-R02_C1d
- 2025_03-Y_Maze-R03_C1a
- 2025_03-Y_Maze-R04_C2i
- 2025_03-Y_Maze-R05_C2d
- 2025_03-Y_Maze-R06_C2a
- 2025_03-Y_Maze-R07_C3i
- 2025_03-Y_Maze-R08_C3d
- 2025_03-Y_Maze-R09_C3n
- 2025_03-Y_Maze-R10_C4i
- 2025_03-Y_Maze-R11_C4d
- 2025_03-Y_Maze-R12_C5i
- 2025_03-Y_Maze-R14_C5a
- 2025_03-Y_Maze-R16_C6i
- 2025_03-Y_Maze-R17_C6d
- 2025_03-Y_Maze-R18_C6a

# Software used to generate the pose estimation files
software: DLC

# List of the tracked bodyparts
bodyparts:
- nose
- left_ear
- right_ear
- head
- neck
- body
- tail_base
- tail_mid
- tail_end
- left_hip
- left_midside
- left_shoulder
- right_hip
- right_midside
- right_shoulder

# List of the exploration targets.
targets:
-

# If your experiment has multiple trials, specify the trial names here.
trials:
- Y_Maze

# Parameters for processing positions
filtering & smoothing:

# Confidence threshold for filtering
  confidence: 2

# Tolerance threshold for filtering
  tolerance: 0.8

# Median filter window size
  median filter: 3

# Video settings
video fps: 30

# Regions of Interest (ROIs) and key points from JSON
roi data:
  frame shape:
    width: 564
    height: 474

  # Scale factor (in px/cm)
  scale: 20

  # Defined ROIs (areas) in the frame
  areas:
  - name: Arm_1
    center:
    - 266
    - 360
    width: 80
    height: 220
    angle: 0
  - name: Arm_2
    center:
    - 120
    - 100
    width: 80
    height: 220
    angle: -60
  - name: Arm_3
    center:
    - 429
    - 105
    width: 80
    height: 220
    angle: 60

  # Key points within the frame
  points:
  - name: arm_end
    center:
    - 64
    - 55
  - name: center
    center:
    - 270
    - 180

# Parameters for geometric analysis
geometric analysis:

  # Maximum nose-target distance to consider exploration.
  distance: 2.5

  # Maximum head-target orientation angle to consider exploration.
  orientation: 45.0

  # Movement threshold for freezing, computed as mean std of all body parts over 1 second.
  freezing threshold: 0.01

# Parameters for automatic analysis
automatic analysis:

  # Model name (simple, wide, RF, etc.)
  model: wide

  # Training date of the model
  model date: example

  # List of bodyparts used to train the model
  model bodyparts:
  - nose
  - L_ear
  - R_ear
  - head
  - neck
  - body

  # Whether to rescale the data
  rescaling: true

  # Whether to reshape the data (set to True for LSTM models))
  reshaping: false

  # Number of past frames to include
  past: 3

  # Number of future frames to include
  future: 3

  # Broaden the window by skipping some frames as we stray further from the present.
  broad: 1.7

# Parameters for the analysis of the experiment
experiment metadata:

  # List of the groups in the experiment
  groups:
  - Group_1
  - Group_2

  # Role/novelty of each target in the experiment
  target roles:
    Hab: null
    TR:
    - Left
    - Right
    TS:
    - Novel
    - Known

  # Type of labels used to measure exploration (geolabels, autolabels, etc.)
  label type: geolabels
