# Rainstorm Parameters file

# Path to the folder containing the pose estimation files
path: C:\Users\dhers\Desktop\Rainstorm\docs\examples\NOR_example

# List of the pose estimation filenames
filenames:
- NOR_Hab_C1_A
- NOR_Hab_C1_B
- NOR_Hab_C1_C
- NOR_Hab_C1_D
- NOR_Hab_C2_A
- NOR_Hab_C2_B
- NOR_Hab_C2_C
- NOR_Hab_C2_D
- NOR_Hab_C3_A
- NOR_Hab_C3_B
- NOR_Hab_C3_C
- NOR_Hab_C3_D
- NOR_Hab_C4_A
- NOR_Hab_C4_B
- NOR_Hab_C4_C
- NOR_Hab_C4_D
- NOR_Hab_C5_A
- NOR_Hab_C5_B
- NOR_Hab_C5_C
- NOR_Hab_C5_D
- NOR_TR_C1_A
- NOR_TR_C1_B
- NOR_TR_C1_C
- NOR_TR_C1_D
- NOR_TR_C2_A
- NOR_TR_C2_B
- NOR_TR_C2_C
- NOR_TR_C2_D
- NOR_TR_C3_A
- NOR_TR_C3_B
- NOR_TR_C3_C
- NOR_TR_C3_D
- NOR_TR_C4_A
- NOR_TR_C4_B
- NOR_TR_C4_C
- NOR_TR_C4_D
- NOR_TR_C5_A
- NOR_TR_C5_B
- NOR_TR_C5_C
- NOR_TR_C5_D
- NOR_TS_C1_A
- NOR_TS_C1_B
- NOR_TS_C1_C
- NOR_TS_C1_D
- NOR_TS_C2_A
- NOR_TS_C2_B
- NOR_TS_C2_C
- NOR_TS_C2_D
- NOR_TS_C3_A
- NOR_TS_C3_B
- NOR_TS_C3_C
- NOR_TS_C3_D
- NOR_TS_C4_A
- NOR_TS_C4_B
- NOR_TS_C4_C
- NOR_TS_C4_D
- NOR_TS_C5_A
- NOR_TS_C5_B
- NOR_TS_C5_C
- NOR_TS_C5_D

# Software used to generate the pose estimation files
software: DLC

# List of the tracked bodyparts
bodyparts:
- nose
- L_ear
- R_ear
- head
- neck
- body
- tail_1
- tail_2
- tail_3

# List of the exploration targets.
targets:
- obj_1
- obj_2

# If your experiment has multiple trials, specify the trial names here.
trials:
- Hab
- TR
- TS

# Parameters for processing positions
filtering & smoothing:
  confidence: 2
  tolerance: 0.8
  median_filter: 3

# Video settings
video_fps: 25

# Regions of Interest (ROIs) and key points from JSON
roi_data:

  # Shape of the video frames
  frame_shape:
    width: 680
    height: 500

  # Scale factor (in px/cm)
  scale: 20

  # Defined ROIs (areas) in the frame
  areas: 
  - name: centre
    center:
    - 340
    - 250
    width: 270
    height: 270
    angle: 30

  # Key points within the frame
  points: null

# Parameters for defining exploration and freezing behavior
geometric analysis:

  # Maximum nose-target distance to consider exploration.
  distance: 2.5

  # Maximum head-target orientation angle to consider exploration.
  orientation: 45.0

  # Movement threshold for freezing, computed as mean std of all body parts over 1 second.
  freezing threshold: 0.01

# Parameters for automatic analysis of the experiment
automatic analysis:

  # Model name (simple, wide, RF, etc.)
  model: wide

  # Training date of the model
  model date: example

  # List of bodyparts used to train the model
  model bodyparts:
  - nose
  - L_ear
  - R_ear
  - head
  - neck
  - body

  # Whether to rescale the data
  rescaling: True

  # Whether to reshape the data (set to True for LSTM models)
  reshaping: True

  # Number of frames to use for past frames
  past: 3

  # Number of frames to use for future frames
  future: 3

  # Window size for the moving average filter
  broad: 1.7

# Parameters for the analysis of the experiment
experiment metadata:

  # List of the groups in the experiment
  groups:
  - 24 hs
  - 1 week

  # Role/novelty of each target in the experiment
  target roles:
    Hab: null
    TR:
    - Left
    - Right
    TS:
    - Novel
    - Known

  # Type of labels used to measure exploration (geolabels, autolabels, etc.)
  label type: autolabels
