# STORM - Simple Tracker for Object Recognition Memory
# Authors: Santiago D'hers. 
# © 2024. This project is openly licensed under the MIT License.
# https://github.com/simple-torm/STORM

# install: conda env create -f STORM_environment.yml

name: STORM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - pip:
    - opencv-python
    - keyboard